- name: nano
  hosts: Linux
  become: true
- name: Update and upgrade apt packages
  apt: null
  upgrade: 'yes'
  update_cache: 'yes'
- name: Get docker script
  uri: null
  url: 'https://get.docker.com'
  method: GET
  dest: get-docker.sh
  follow_redirects: safe
