---
- hosts: Linux
  become: true
  
  - name: nano
    hosts: Linux
    become: true
    tasks:
      - name: ensure nano is there
        apt:
         name: nano
         state: latest
