version: "2.4"
services:
    wyze-bridge:
        container_name: wyze-bridge
        restart: unless-stopped
        image: mrlt8/wyze-bridge:latest
        ports:
            - 1935:1935 # RTMP
            - 8554:8554 # RTSP
            - 8888:8888 # HLS
            - 8889:8889 #WebRTC
            - 8189:8189/udp # WebRTC/ICE
            - 5000:5000 # WEB-UI
        environment:
            - WYZE_EMAIL=
            - WYZE_PASSWORD=
            - WB_IP=192.168.1.107
            - ENABLE_AUDIO=False
            - SUBSTREAM=True
            #- MQTT_HOST=
            #- MQTT_AUTH=
            #- MQTT_TOPIC=